version: '3'

services:
  app:
    stdin_open: true
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"

  mongo:
    stdin_open: true
    image: mongo:4.2.15
    ports:
      - "27017:27017"

  seeder:
    stdin_open: true
    depends_on:
      - mongo
    command: ["sh", "seed.sh"]
    build:
      context: .
      dockerfile: docker/SeederDockerfile
    volumes:
      - ./docker/seeds:/data/db
      - ./docker/config/seed.sh:/seed.sh

